### ISSUE TITLE
would data be available?

### ISSUE THREAD

**Issue by whaleloops** [bowang-lab/clinical-camel#1]
Especially the artificial data using ClinicalArticles and MedQA

**Comment by whaleloops** [comment]
Sorry if I missed this, what is the teacher model? GPT-4?

**Comment by augustintoma** [comment]
will be updating the repo in the next day or so with additional code to clarify everything, but in the paper we used GPT-3.5 to create the dialogues and then used GPT-4 as an evaluator,
